CREATE TABLE draws
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_id       VARCHAR(32) NOT NULL UNIQUE,
    draw_date     DATE        NOT NULL,
    main_numbers  VARCHAR(64) NOT NULL,
    bonus_numbers VARCHAR(32) NOT NULL
);
