-- Drop for dev runs (HSQL memory)
DROP TABLE IF EXISTS draw;

-- Core table
CREATE TABLE draw
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_id       VARCHAR(20) NOT NULL, -- äriline ID (kasutame kuupäeva stringi)
    draw_date     DATE        NOT NULL,
    main_numbers  VARCHAR(50) NOT NULL, -- "1 4 7 12 33 40" (6 numbrit)
    bonus_numbers VARCHAR(10) NOT NULL  -- "2" (1 number)
);

-- Business rule: draw_id is unique
CREATE UNIQUE INDEX ux_draw_draw_id ON draw (draw_id);

-- Searches/analytics by date
CREATE INDEX ix_draw_date ON draw (draw_date);

